# change application port
server:
  port: 8081


# broker config
spring:
  activemq:
    broker-url: tcp://broker-consumers-ss-1.broker-consumers-hdls-svc.bus-broker-cluster.svc.cluster.local:61616
    username: hsGCbwFB
    password: PyG0g7eE
    packages:
      trust-all: true
  artemis:
    embedded:
      queues: queue-data
