# change application port
server:
  port: 8082


# broker config
spring:
  activemq:
    broker-url: tcp://broker-consumers-wconsj-1-svc-bus-broker-cluster.svc.cluster.local:8161
    username: hsGCbwFB
    password: PyG0g7eE
    packages:
      trust-all: true
  artemis:
    embedded:
      queues: queue-test
