# change application port
server:
  port: 8082


# broker config
spring:
  activemq:
    broker-url: tcp://172.30.115.236:8161
    username: hsGCbwFB
    password: PyG0g7eE
    packages:
      trust-all: true
  artemis:
    embedded:
      queues: queue-test
